### PR TITLE
x11-terms/cool-retro-term-9999.ebuild fix

### PR DESCRIPTION
**Pull request by dwatzke**
added a missing dep & enabled git submodule checkout so it actually works

### CODE REVIEW

**Comment by dwatzke** [comment]
please change qmake-qt5 to /usr/lib/qt5/bin/qmake

I messed up, thinking this was a symlink from an ebuild but it's not.

thanks

**Comment by megabaks** [comment]
i can't - pc dead
27.01.2015 23:29 пользователь "David Watzke" <notifications@github.com>
написал:

**Comment by dwatzke** [comment]
well, when you get the chance :)
also, instead of just
dev-qt/qtquickcontrols:5
there should be this dep:
dev-qt/qtquickcontrols:5[widgets]

thanks!

**Comment by dwatzke** [comment]
I've created another pull request to fix this (don't really know why I didn't do that in the first place)
https://github.com/megabaks/stuff/pull/61

**Pull request merged**
